language: node_js
sudo: false
node_js:
  - "6.1"
rvm:
  - 2.2
  - 2.1
script:
  - jekyll build
install:
  - npm install -g firebase-tools
  - gem install jekyll
deploy:
  provider: script
  script: firebase deploy
  on:
    branch: master
