language: ruby
sudo: false
env:
  - TRAVIS_NODE_VERSION="6.1"
rvm:
  - 2.5.0
  - 2.4.3
  - 2.3.3
script:
  - jekyll --version
  - jekyll build
  - htmlproofer ./_site
install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install -g firebase-tools firebase-bolt
  - bundle install
deploy:
  provider: script
  script: firebase deploy
  skip_cleanup: true
  on:
    branch: master
