sudo: false
install:
- curl -LSfs https://japaric.github.io/trust/install.sh | sh -s -- --git cobalt-org/cobalt.rs
  --crate cobalt --force --target x86_64-unknown-linux-gnu --tag v0.15.11
- export PATH="$PATH:~/.cargo/bin"
script:
- cobalt --version
- cobalt build
deploy:
  provider: firebase
  message: "Travis CI Automatic Deployment"
  token:
    secure: Mm1vOpHOBlU9NAJXCuvxg2fz6avWxizmfOtwXIkjH7BTSOr6FtuFxEDgzGsF6JvQLi+qdLb+wQW49LlESHAiEz+DDo/6Z5i5Kni5nv5wboSMEg9saoYiIe3gn71o+2JX5z9YQx9SHIGJX3afF8/6WJ8/NeH2NvZVJ+tXkNtW9O2wl+ncOjfMNE2UEJihZa5T84S6liqdFbx9Hm3pI8NZZWYT2LN4cb7IpZp++NBNT1e+W0jsWAS9w+omY94KvDNBgEDmkYOvoZ70617rKB+1fDfd7aJh9SS9043tHdWls2xFjZDafuAKJMXRMT2GVxDdW8kIjH5+uwPT/P7BjlhWa0RGJfNx86q5v1ZMgQLcDsF+33n7YjN6OZEkYsVe68wMh+eUyHlCN0vL7vYIb/nR4ZmnOb99uyyMlaWaFCRD5KfwX5ryIdY5g3LcgLP6FpSKmy4eyj/q7+asCNSedf4QF8eAq1YFi236ic5yiyBhYXs/b4PO1RWbRFNJECyos6HfRsyx+kIus92hONIgbUMvWviQ2L7KirDlEZ5Osj4+XbekQ7E3iVfphiPP2SC5QrCCoV3OzdSzWPIsqk5H2NIRzj9lJ7wxThLPbPgrx3LfXK53Se3/5FyrU+HJ80kU9XXUoolNYca/UuVqrMgddtdhfgaoqS7mOkesHKL8OUZUxBI=
  on:
    branch: master
