sudo: false
before_script:
  - curl -LSfs https://japaric.github.io/trust/install.sh |
    sh -s --
    --git cobalt-org/cobalt.rs
    --crate cobalt
    --force
    --target x86_64-unknown-linux-gnu
    --tag v0.15.11
  - export PATH="$PATH:~/.cargo/bin"
script:
  - cobalt --version
  - cobalt build
deploy:
  provider: script
  script: firebase login --token "$FIREBASE_TOKEN" && firebase deploy
  skip_cleanup: true
  on:
    branch: master
