# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Xen Relay
email: webmaster@xenrelay.com
description: > # this means to ignore newlines until "baseurl:"
  A personal website waiting to be constructed.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.xenrelay.com" # the base hostname & protocol for your site
tag_url: '/blog/tag'

# For a project page here should be a project name. Otherwise (for user's/organizaion's page leave it empty)
baseurl: ''

share:
  facebook: false
  twitter: false
  gplus: false
  linkedin: false
  pinterest: false
  email: false

social:
  github: proegssilb
  rss: feed.xml


# Individual posts can override 'comments' to disable on a post-by-post basis
comments: true

permalink: /blog/:year/:month/:title.html

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
#paginate: 3

# Build settings
markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: false

exclude:
  - database.rules.json
  - firebase.json
  - README.md
  - LICENSE
  - firebase-debug.log
  - Gemfile
  - Gemfile.lock
  - xenrelay.bolt
